name: verify

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: pnpm/action-setup@v2
        with:
          version: 6.2.1
    - name: install
      run: pnpm install
    - name: test
      run: pnpm test
