name: version

on:
  push:
    paths:
      - package.json

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: check
        name: check
        run: NEW_VERSION=$(git diff -U0 HEAD~ -- package.json | grep -Po "(?<=\+\s{2}\"version\"\:\s\")([^\"]+)"); echo "::set-output name=new_version::$NEW_VERSION"
      - if: steps.check.outputs.new_version != ''
        name: tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{steps.check.outputs.new_version}}",
              sha: "${{github.sha}}"
            })
